export class Spesific {
  public static fa2finglish(str: string) {
    return str.replace('آ', 'a')
      .replace('أ', 'a')
      .replace('إ', 'e')
      .replace('ب', 'b')
      .replace('پ', 'p')
      .replace('ت', 't')
      .replace('ث', 's')
      .replace('ج', 'j')
      .replace('چ', 'ch')
      .replace('ح', 'h')
      .replace('خ', 'kh')
      .replace('د', 'd')
      .replace('ذ', 'z')
      .replace('ر', 'r')
      .replace('ز', 'z')
      .replace('ژ', 'zh')
      .replace('س', 's')
      .replace('ش', 'sh')
      .replace('ص', 's')
      .replace('ض', 'z')
      .replace('ط', 't')
      .replace('ظ', 'z')
      .replace('ع', 'ea')
      .replace('غ', 'gh')
      .replace('ف', 'f')
      .replace('ق', 'gh')
      .replace('ک', 'k')
      .replace('گ', 'g')
      .replace('ل', 'l')
      .replace('م', 'm')
      .replace('ن', 'n')
      .replace('و', 'v')
      .replace('ه', 'h')
      .replace('ی', 'y')
      .replace('ي', 'y')
      .replace('ئ', 'wa')
      .replace('ء', 'wa')
      .replace('ة', 't')
      .replace('ؤ', 'w')
      .replace('؟', '?')
      .replace('ك', 'k')


      .replace('ّ', '')
      .replace('َ', '')
      .replace('ِ', '')
      .replace('ُ', '')
      .replace('ً', '')
      .replace('ٍ', '')
      .replace('ٌ', '')
      .replace('ٌ', '')
      .replace('ْ', '')
      .replace('ٓ', '')
      .replace('ٰ', '')
      .replace('ٔ', '')
      .replace('‌', '');
  }
}
